// <auto-generated />
using System;
using ExceptionStoringServiceClassicWebApp.Models.DataModels.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExceptionStoringServiceClassicWebApp.Migrations
{
    [DbContext(typeof(ServiceDBContext))]
    partial class ServiceDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7");

            modelBuilder.Entity("ExceptionStoringServiceClassicWebApp.Models.DataModels.AppInfo", b =>
                {
                    b.Property<int>("AppInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppGUID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppInfoId");

                    b.ToTable("AppInfos");
                });

            modelBuilder.Entity("ExceptionStoringServiceClassicWebApp.Models.DataModels.AppVersion", b =>
                {
                    b.Property<int>("AppVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppInfoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppVersionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppVersionId");

                    b.HasIndex("AppInfoId");

                    b.ToTable("AppVersions");
                });

            modelBuilder.Entity("ExceptionStoringServiceClassicWebApp.Models.DataModels.ExeptionData", b =>
                {
                    b.Property<long>("ExeptionDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExeptionStackTrase")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExeptionType")
                        .HasColumnType("TEXT");

                    b.Property<int?>("HResult")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("InnerExeptioId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InnerExeptionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<int>("MessageHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SeriaizedData")
                        .HasColumnType("TEXT");

                    b.Property<int>("SeriaizedDataHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<int>("StackTraceHash")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StackTraseHash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TargetSite")
                        .HasColumnType("TEXT");

                    b.Property<int?>("TargetSiteHash")
                        .HasColumnType("INTEGER");

                    b.HasKey("ExeptionDataId");

                    b.HasIndex("AppId");

                    b.HasIndex("AppVersionId");

                    b.ToTable("ExptionsDatas");
                });

            modelBuilder.Entity("ExceptionStoringServiceClassicWebApp.Models.DataModels.AppVersion", b =>
                {
                    b.HasOne("ExceptionStoringServiceClassicWebApp.Models.DataModels.AppInfo", "AppInfo")
                        .WithMany()
                        .HasForeignKey("AppInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppInfo");
                });

            modelBuilder.Entity("ExceptionStoringServiceClassicWebApp.Models.DataModels.ExeptionData", b =>
                {
                    b.HasOne("ExceptionStoringServiceClassicWebApp.Models.DataModels.AppInfo", "App")
                        .WithMany()
                        .HasForeignKey("AppId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ExceptionStoringServiceClassicWebApp.Models.DataModels.AppVersion", "AppVersion")
                        .WithMany()
                        .HasForeignKey("AppVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("App");

                    b.Navigation("AppVersion");
                });
#pragma warning restore 612, 618
        }
    }
}
